# fly.toml app configuration file generated for node-argo on 2026-05-13T03:33:53Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'node-argo'
primary_region = 'lax'

[http_service]
  auto_start_machines = true
  auto_stop_machines = false
  force_https = true
  internal_port = 3000
  min_machines_running = 1
  processes = ['app']

[[vm]]
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 256
